options:
  cluster_name:
    type: string
    default: cluster1
    description: >-
      'Name to be recorded in database for jobs from this cluster.  This is
      important if a single database is used to record information  from
      multiple Slurm-managed clusters.'
  DebugFlags:
    type: string
    default: ""
    description: >-
      'Defines specific subsystems which should provide more detailed event logging.
      Multiple subsystems can be specified with comma separators. Most DebugFlags 
      will result in verbose logging for the identified subsystems and could impact performance.
      Full list of options found in https://slurm.schedmd.com/slurm.conf.html'
  custom_config:
    type: string
    default: ""
    description: >-
      'User supplied slurm confinguration'
  proctrack_type:
    type: string
    default: proctrack/linuxproc
    description: >-
      'Identifies the plugin to be used for process tracking on a job step basis.'
  node_weight_criteria:
    type: string
    default: none
    description: >-
      'What type of node criteria to use for setting weights on nodes.
      By default all nodes have Weight=1. When it is preferable to
      allocate for example smaller memory nodes for smaller jobs, low
      weights should be assigned to smaller nodes. Setting this charm
      option will automatically order and weigh the nodes in ascending
      order. Allowed values are RealMemory, CPUs and CoresPerSocket.'
