options:
  partition-default:
    type: string
    default: ""
    description: >-
      'The default partion for the node will be set to NO if left blank. If supplied with a value slurm.conf will be
      render slurm.conf default_partion value with YES'
  partition-name:
    type: string
    default: partition1
    description: >-
      'Name by which the partition may be referenced (e.g. "Interactive"). This
      name can be specified by users when submitting jobs. If the PartitionName
      is "DEFAULT", the values specified with that record will apply to
      subsequent partition specifications unless explicitly set to other values
      in that partition record or replaced with a different set of default
      values. Each line where PartitionName is "DEFAULT" will replace or add to
      previous default values and not a reinitialize the default values.'
  partition-config:
    type: string
    default: ""
    description: >-
      'Extra partition configuration specified as a space separated key=value single line.'
  snap-store-channel:
    type: string
    description: snap store channel to install slurm snap from
    default: "stable"
