options:
  partition-default:
    type: boolean
    default: true
    description: >-
      'If this is True, jobs submitted without a partition specification
      will utilize this partition.'
  partition-name:
    type: string
    default: partition1
    description: >-
      'Name by which the partition may be referenced (e.g. "Interactive"). This
      name can be specified by users when submitting jobs. If the PartitionName
      is "DEFAULT", the values specified with that record will apply to
      subsequent partition specifications unless explicitly set to other values
      in that partition record or replaced with a different set of default
      values. Each line where PartitionName is "DEFAULT" will replace or add to
      previous default values and not a reinitialize the default values.'
  partition-config:
    type: string
    default: ""
    description: >-
      'Extra partition configuration specified as a space separated key=value single line.'
  snap-store-channel:
    type: string
    description: snap store channel to install slurm snap from
    default: "stable"
